name: ChestEvent
main: com.siwek9.main.ChestEvent
version: 0.2.0
api-version: 1.20
api: 4.0.0
author: siwek9
commands:
  event:
    description: This is a demo command.
    usage: §c<command> <create | remove | edit | info | start> <Event Name> [Json options]
    