name: ChestEvent
main: com.siwek9.main.ChestEvent
version: 0.1.0
author: siwek9
commands:
  event:
    description: This is a demo command.
    usage: /<command> [player]
    permission: chestevent.command
    permission-message: You don't have <permission>
    